stages:
  prepare:
    cmd: python3 postcode/prepare.py input/onspd.csv.gz
    deps:
    - input/onspd.csv.gz
    - postcode/config.py
    - postcode/prepare.py
    outs:
    - working/
  build:
    cmd: python3 postcode/build.py output/onspd-extract.csv
    deps:
    - postcode/build.py
    - postcode/config.py
    - working/postcodes.parquet
    outs:
    - output/onspd-extract.csv
