stages:
  prepare:
    cmd: python3 postcode/prepare.py input/onspd.csv
    deps:
    - input/onspd.csv
    - postcode/config.py
    - postcode/prepare.py
    outs:
    - working/
  build:
    cmd: python3 postcode/build.py
    deps:
    - postcode/build.py
    - postcode/config.py
    - working/
    outs:
    - output/
